version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: restka
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: masjiddb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
